### ISSUE TITLE
After level change RGL visualise old terrain

### ISSUE THREAD

**Issue by patrykantosz** [RobotecAI/o3de-rgl-gem#29]
After changing the level from the one with terrain to some new one (without restarting o3de editor) I got strange visualization - it looks like rgl somehow remember the old terrain and "draw" it above the current one. Everything works fine when I close O3DE and rerun it with new level. Hopefully the screenshot says more than this description.
![Screenshot from 2024-06-25 15-17-44](https://github.com/RobotecAI/o3de-rgl-gem/assets/37815610/d5ce5e88-d9dd-4f03-b2a0-3f8e933b0674)

**Comment by alek-kam-robotec-ai** [comment]
Thanks for the report. I've reproduced this on my local machine and will soon create a fix.
