### ISSUE TITLE
Cannot use RGL with O3DE stabilization

### ISSUE THREAD

**Issue by jhanca-robotecai** [RobotecAI/o3de-rgl-gem#47]
I created two PRs to fix missing dependency versions:
1. PR #42 targeting the `development` branch, which sets the requirement for RGL to use `development` branch of O3DE
2. PR #43 targeting the `main` branch, which sets the requirement for RGL to use stable O3DE or the next stable (in development, but feature-locked already).

My second PR #43 was force-pushed and modified (!?) to link `main` version of RGL with `main` version of O3DE. As a result is it **IMPOSSIBLE** to use RGL with the stabilization branch of O3DE. Please note, that O3DE is to be released within a month, the stabilization branch is feature-locked and many developers use it on a daily basis.

**Comment by alek-kam-robotec-ai** [comment]
The gem was not tested or intended to be used with the o3de-extras stabilization. If there exists such need this could however be changed.
